name: Minecraft Forge CI (Java)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.1.0
      with:
        java-version: 1.8
    - name: Set Gradle Permissions
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
